[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache"
