import { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun } from 'docx';
import { createMediaObjectUrl, isLegacyMediaRef } from './mediaStore';
import { collectTripPhotos } from './tripPhotos';
import {
  ensurePhotoPlaceholders,
  findPhotoForPlaceholder,
  parseNarrativeSegments,
} from './recapNarrative';

const DOCX_IMAGE_WIDTH = 420;
const EMAIL_DOCX_IMAGE_WIDTH = 240;
/** Netlify function request body limit is ~6 MB; stay under with headroom. */
export const MAX_EMAIL_PAYLOAD_BYTES = 5.5 * 1024 * 1024;

export async function buildTripReportDocx(trip, narrativeText, options = {}) {
  const forEmail = Boolean(options.forEmail);
  const imageWidth = forEmail ? EMAIL_DOCX_IMAGE_WIDTH : DOCX_IMAGE_WIDTH;
  const imageLoadOpts = forEmail
    ? { maxWidth: imageWidth, preferThumb: true, compress: true }
    : { maxWidth: imageWidth, preferThumb: false, compress: false };

  const wovenText = ensurePhotoPlaceholders(trip, narrativeText);
  const title = trip?.name || 'Trip Report';
  const meta = [
    trip?.location,
    formatDateRange(trip),
    (trip?.types || []).join(', '),
  ].filter(Boolean).join(' · ');

  const allPhotos = collectTripPhotos(trip);
  const usedPhotoIds = new Set();
  const segments = parseNarrativeSegments(wovenText);

  const children = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: title, bold: true, size: 52 })],
    }),
  ];

  if (meta) {
    children.push(new Paragraph({
      children: [new TextRun({ text: meta, size: 22, color: '555555' })],
      spacing: { after: 300 },
    }));
  }

  for (const seg of segments) {
    if (seg.type === 'photo') {
      const photo = findPhotoForPlaceholder(allPhotos, seg, usedPhotoIds);
      if (photo) await appendTripPhoto(children, photo, usedPhotoIds, imageWidth, imageLoadOpts);
      continue;
    }

    const blocks = seg.content.split(/\n{2,}/).map((b) => b.trim()).filter(Boolean);
    for (const block of blocks) {
      const lines = block.split('\n');
      const first = lines[0];
      const isHeading = lines.length === 1 && first.length < 80 && !first.endsWith('.');
      if (isHeading && (first === 'Summary' || first === 'Closing' || /^Day \d/i.test(first) || first.length < 48)) {
        children.push(new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: first, bold: true, size: 28 })],
          spacing: { before: 240, after: 120 },
        }));
        if (lines.length > 1) {
          children.push(bodyParagraph(lines.slice(1).join('\n')));
        }
      } else {
        children.push(bodyParagraph(block));
      }
    }
  }

  children.push(new Paragraph({
    children: [new TextRun({ text: `Generated by TripReport · ${new Date().toLocaleString()}`, size: 18, color: '888888' })],
    spacing: { before: 400 },
  }));

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBlob(doc);
}

export async function downloadTripReportDocx(trip, narrativeText) {
  const blob = await buildTripReportDocx(trip, narrativeText);
  const name = `${slugify(trip?.name || 'trip')}-report.docx`;
  triggerDownload(blob, name);
  return blob;
}

export async function docxBlobToBase64(blob) {
  const buffer = await blob.arrayBuffer();
  return arrayBufferToBase64(buffer);
}

/** Gzip-compress docx for email transport (Netlify ~6 MB request limit). */
export async function encodeDocxForEmailTransport(blob) {
  const rawBase64 = await docxBlobToBase64(blob);

  if (typeof CompressionStream !== 'undefined') {
    const gzBlob = await gzipBlob(blob);
    const compressed = {
      encoding: 'gzip',
      docxBase64: await docxBlobToBase64(gzBlob),
    };
    const jsonBytes = estimateEmailJsonBytes(compressed);
    if (jsonBytes <= MAX_EMAIL_PAYLOAD_BYTES) return compressed;
  }

  const raw = { encoding: 'raw', docxBase64: rawBase64 };
  const jsonBytes = estimateEmailJsonBytes(raw);
  if (jsonBytes > MAX_EMAIL_PAYLOAD_BYTES) {
    throw new Error('Report is too large to email (try Download .docx, or use fewer photos).');
  }
  return raw;
}

function estimateEmailJsonBytes({ encoding, docxBase64 }) {
  return new Blob([JSON.stringify({ encoding, docxBase64, to: 'x', tripName: 'x', fileName: 'x-report.docx' })]).size;
}

async function gzipBlob(blob) {
  const stream = blob.stream().pipeThrough(new CompressionStream('gzip'));
  return new Response(stream).blob();
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

async function appendTripPhoto(children, photo, usedPhotoIds, imageWidth, imageLoadOpts) {
  const img = await loadImageForDocx(photo.media, imageLoadOpts);
  if (!img) return;

  usedPhotoIds.add(photo.id);
  children.push(photoParagraph(img, imageWidth));

  const caption = photo.caption || photo.locationName || photo.eventName;
  if (caption) {
    children.push(new Paragraph({
      children: [new TextRun({ text: caption, size: 20, italics: true, color: '666666' })],
      spacing: { after: 240 },
    }));
  }
}

function photoParagraph(img, imageWidth) {
  return new Paragraph({
    children: [
      new ImageRun({
        data: img.data,
        transformation: { width: imageWidth, height: Math.max(1, Math.round(imageWidth * img.aspect)) },
        type: img.type,
      }),
    ],
    spacing: { after: 80 },
  });
}

function bodyParagraph(text) {
  return new Paragraph({
    children: [new TextRun({ text, size: 24 })],
    spacing: { after: 200 },
  });
}

async function loadImageForDocx(media, { maxWidth = DOCX_IMAGE_WIDTH, preferThumb = false, compress = false } = {}) {
  try {
    if (isLegacyMediaRef(media)) {
      const src = media.dataUrl || media.thumbDataUrl;
      if (!src) return null;
      if (compress) return canvasToDocxImage(src, { maxSide: maxWidth * 2, quality: 0.78 });
      return dataUrlToDocxImage(src);
    }
    if (!media?.id) return null;

    const order = preferThumb ? [true, false] : [false, true];
    for (const thumb of order) {
      const url = await createMediaObjectUrl(media.id, { preferThumb: thumb });
      if (!url) continue;
      try {
        if (compress) return await canvasToDocxImage(url, { maxSide: maxWidth * 2, quality: 0.78 });
        const res = await fetch(url);
        const blob = await res.blob();
        const buffer = await blob.arrayBuffer();
        const dims = await measureImage(url);
        return {
          data: new Uint8Array(buffer),
          type: blob.type?.includes('png') ? 'png' : 'jpg',
          aspect: dims.height / dims.width,
        };
      } finally {
        URL.revokeObjectURL(url);
      }
    }
    return null;
  } catch {
    return null;
  }
}

function canvasToDocxImage(src, { maxSide, quality }) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      try {
        const ratio = Math.min(1, maxSide / Math.max(img.width, img.height));
        const w = Math.max(1, Math.round(img.width * ratio));
        const h = Math.max(1, Math.round(img.height * ratio));
        const canvas = document.createElement('canvas');
        canvas.width = w;
        canvas.height = h;
        canvas.getContext('2d').drawImage(img, 0, 0, w, h);
        canvas.toBlob(async (blob) => {
          if (!blob) {
            reject(new Error('Could not compress image'));
            return;
          }
          const buffer = await blob.arrayBuffer();
          resolve({
            data: new Uint8Array(buffer),
            type: 'jpg',
            aspect: h / w,
          });
        }, 'image/jpeg', quality);
      } catch (e) {
        reject(e);
      }
    };
    img.onerror = () => reject(new Error('Image load failed'));
    img.src = src;
  });
}

async function dataUrlToDocxImage(dataUrl) {
  const res = await fetch(dataUrl);
  const blob = await res.blob();
  const buffer = await blob.arrayBuffer();
  const dims = await measureImage(dataUrl);
  return {
    data: new Uint8Array(buffer),
    type: blob.type?.includes('png') ? 'png' : 'jpg',
    aspect: dims.height / dims.width,
  };
}

function measureImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve({ width: img.width, height: img.height });
    img.onerror = reject;
    img.src = src;
  });
}

function formatDateRange(trip) {
  const start = trip?.startDate;
  const end = trip?.endDate || (trip?.endedAt ? new Date(trip.endedAt).toISOString().slice(0, 10) : null);
  if (start && end) return `${start} → ${end}`;
  if (start) return start;
  return '';
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'trip';
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
