import { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun } from 'docx';
import { createMediaObjectUrl, isLegacyMediaRef } from './mediaStore';
import { collectTripPhotos } from './tripPhotos';

const DOCX_IMAGE_WIDTH = 420;

export async function buildTripReportDocx(trip, narrativeText) {
  const title = trip?.name || 'Trip Report';
  const meta = [
    trip?.location,
    formatDateRange(trip),
    (trip?.types || []).join(', '),
  ].filter(Boolean).join(' · ');

  const allPhotos = collectTripPhotos(trip);
  const usedPhotoIds = new Set();

  const children = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: title, bold: true, size: 52 })],
    }),
  ];

  if (meta) {
    children.push(new Paragraph({
      children: [new TextRun({ text: meta, size: 22, color: '555555' })],
      spacing: { after: 300 },
    }));
  }

  if (trip?.coverPhoto) {
    const cover = await loadImageForDocx(trip.coverPhoto);
    if (cover) {
      children.push(photoParagraph(cover));
      if (trip.coverPhoto.id) usedPhotoIds.add(trip.coverPhoto.id);
    }
  }

  const blocks = String(narrativeText || '').split(/\n{2,}/);
  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;
    const lines = trimmed.split('\n');
    const first = lines[0];
    const isHeading = lines.length === 1 && first.length < 80 && !first.endsWith('.');
    if (isHeading && (first === 'Summary' || first === 'Closing' || /^Day \d/i.test(first) || first.length < 48)) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: first, bold: true, size: 28 })],
        spacing: { before: 240, after: 120 },
      }));
      if (lines.length > 1) {
        await appendTextWithPhotos(children, lines.slice(1).join('\n'), allPhotos, usedPhotoIds);
      }
    } else {
      await appendTextWithPhotos(children, trimmed, allPhotos, usedPhotoIds);
    }
  }

  const unused = allPhotos.filter((p) => !usedPhotoIds.has(p.id));
  if (unused.length > 0) {
    children.push(new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: 'Photos from the trip', bold: true, size: 32 })],
      spacing: { before: 360, after: 200 },
    }));

    const byDay = groupPhotosByDay(unused);
    for (const [day, photos] of byDay) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: formatDayHeading(day), bold: true, size: 26 })],
        spacing: { before: 200, after: 120 },
      }));
      for (const photo of photos) {
        await appendTripPhoto(children, photo, usedPhotoIds);
      }
    }
  }

  children.push(new Paragraph({
    children: [new TextRun({ text: `Generated by TripReport · ${new Date().toLocaleString()}`, size: 18, color: '888888' })],
    spacing: { before: 400 },
  }));

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBlob(doc);
}

export async function downloadTripReportDocx(trip, narrativeText) {
  const blob = await buildTripReportDocx(trip, narrativeText);
  const name = `${slugify(trip?.name || 'trip')}-report.docx`;
  triggerDownload(blob, name);
  return blob;
}

export async function docxBlobToBase64(blob) {
  const buffer = await blob.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

async function appendTextWithPhotos(children, text, allPhotos, usedPhotoIds) {
  const re = /\[Photo:\s*([^\]]+)\]/gi;
  if (!re.test(text)) {
    children.push(bodyParagraph(text));
    return;
  }

  re.lastIndex = 0;
  let lastIndex = 0;
  let match;
  while ((match = re.exec(text)) !== null) {
    const before = text.slice(lastIndex, match.index).trim();
    if (before) children.push(bodyParagraph(before));
    const photo = matchPhoto(allPhotos, match[1], usedPhotoIds);
    if (photo) await appendTripPhoto(children, photo, usedPhotoIds);
    lastIndex = re.lastIndex;
  }

  const tail = text.slice(lastIndex).trim();
  if (tail) children.push(bodyParagraph(tail));
}

async function appendTripPhoto(children, photo, usedPhotoIds) {
  const img = await loadImageForDocx(photo.media);
  if (!img) return;

  usedPhotoIds.add(photo.id);
  children.push(photoParagraph(img));

  const caption = photo.caption || photo.locationName || photo.eventName;
  if (caption) {
    children.push(new Paragraph({
      children: [new TextRun({ text: caption, size: 20, italics: true, color: '666666' })],
      spacing: { after: 240 },
    }));
  }
}

function photoParagraph(img) {
  return new Paragraph({
    children: [
      new ImageRun({
        data: img.data,
        transformation: { width: DOCX_IMAGE_WIDTH, height: Math.max(1, Math.round(DOCX_IMAGE_WIDTH * img.aspect)) },
        type: img.type,
      }),
    ],
    spacing: { after: 80 },
  });
}

function matchPhoto(photos, label, usedPhotoIds) {
  const q = label.trim().toLowerCase();
  if (!q) return null;

  const candidates = photos.filter((p) => !usedPhotoIds.has(p.id));
  const exact = candidates.find((p) => (p.caption || '').toLowerCase() === q);
  if (exact) return exact;

  const partial = candidates.find((p) => {
    const cap = (p.caption || '').toLowerCase();
    const loc = (p.locationName || '').toLowerCase();
    const ev = (p.eventName || '').toLowerCase();
    return cap.includes(q) || q.includes(cap)
      || (loc && (q.includes(loc) || loc.includes(q)))
      || (ev && (q.includes(ev) || ev.includes(q)));
  });
  if (partial) return partial;

  return candidates[0] || null;
}

function groupPhotosByDay(photos) {
  const byDay = new Map();
  for (const p of photos) {
    const day = p.day || 'unknown';
    if (!byDay.has(day)) byDay.set(day, []);
    byDay.get(day).push(p);
  }
  return [...byDay.entries()].sort(([a], [b]) => a.localeCompare(b));
}

function formatDayHeading(dayKey) {
  if (!dayKey || dayKey === 'unknown') return 'Undated photos';
  const d = new Date(`${dayKey}T12:00:00`);
  if (Number.isNaN(d.getTime())) return dayKey;
  return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
}

function bodyParagraph(text) {
  return new Paragraph({
    children: [new TextRun({ text, size: 24 })],
    spacing: { after: 200 },
  });
}

async function loadImageForDocx(media) {
  try {
    if (isLegacyMediaRef(media)) {
      const src = media.dataUrl || media.thumbDataUrl;
      if (!src) return null;
      return dataUrlToDocxImage(src);
    }
    if (!media?.id) return null;

    for (const preferThumb of [false, true]) {
      const url = await createMediaObjectUrl(media.id, { preferThumb });
      if (!url) continue;
      try {
        const res = await fetch(url);
        const blob = await res.blob();
        const buffer = await blob.arrayBuffer();
        const dims = await measureImage(url);
        return {
          data: new Uint8Array(buffer),
          type: blob.type?.includes('png') ? 'png' : 'jpg',
          aspect: dims.height / dims.width,
        };
      } finally {
        URL.revokeObjectURL(url);
      }
    }
    return null;
  } catch {
    return null;
  }
}

async function dataUrlToDocxImage(dataUrl) {
  const res = await fetch(dataUrl);
  const blob = await res.blob();
  const buffer = await blob.arrayBuffer();
  const dims = await measureImage(dataUrl);
  return {
    data: new Uint8Array(buffer),
    type: blob.type?.includes('png') ? 'png' : 'jpg',
    aspect: dims.height / dims.width,
  };
}

function measureImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve({ width: img.width, height: img.height });
    img.onerror = reject;
    img.src = src;
  });
}

function formatDateRange(trip) {
  const start = trip?.startDate;
  const end = trip?.endDate || (trip?.endedAt ? new Date(trip.endedAt).toISOString().slice(0, 10) : null);
  if (start && end) return `${start} → ${end}`;
  if (start) return start;
  return '';
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'trip';
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
