import { Document, Packer, Paragraph, TextRun, HeadingLevel, ImageRun } from 'docx';
import { createMediaObjectUrl, isLegacyMediaRef } from './mediaStore';

export async function buildTripReportDocx(trip, narrativeText) {
  const title = trip?.name || 'Trip Report';
  const meta = [
    trip?.location,
    formatDateRange(trip),
    (trip?.types || []).join(', '),
  ].filter(Boolean).join(' · ');

  const children = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: title, bold: true, size: 52 })],
    }),
  ];

  if (meta) {
    children.push(new Paragraph({
      children: [new TextRun({ text: meta, size: 22, color: '555555' })],
      spacing: { after: 300 },
    }));
  }

  if (trip?.coverPhoto) {
    const cover = await loadImageForDocx(trip.coverPhoto);
    if (cover) {
      children.push(new Paragraph({
        children: [
          new ImageRun({
            data: cover.data,
            transformation: { width: 420, height: Math.round(420 * cover.aspect) },
            type: cover.type,
          }),
        ],
        spacing: { after: 200 },
      }));
    }
  }

  const blocks = String(narrativeText || '').split(/\n{2,}/);
  for (const block of blocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;
    const lines = trimmed.split('\n');
    const first = lines[0];
    const isHeading = lines.length === 1 && first.length < 80 && !first.endsWith('.');
    if (isHeading && (first === 'Summary' || first === 'Closing' || /^Day \d/i.test(first) || first.length < 48)) {
      children.push(new Paragraph({
        heading: HeadingLevel.HEADING_2,
        children: [new TextRun({ text: first, bold: true, size: 28 })],
        spacing: { before: 240, after: 120 },
      }));
      if (lines.length > 1) {
        children.push(bodyParagraph(lines.slice(1).join('\n')));
      }
    } else {
      children.push(bodyParagraph(trimmed));
    }
  }

  children.push(new Paragraph({
    children: [new TextRun({ text: `Generated by TripReport · ${new Date().toLocaleString()}`, size: 18, color: '888888' })],
    spacing: { before: 400 },
  }));

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBlob(doc);
}

export async function downloadTripReportDocx(trip, narrativeText) {
  const blob = await buildTripReportDocx(trip, narrativeText);
  const name = `${slugify(trip?.name || 'trip')}-report.docx`;
  triggerDownload(blob, name);
  return blob;
}

export async function docxBlobToBase64(blob) {
  const buffer = await blob.arrayBuffer();
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

function bodyParagraph(text) {
  return new Paragraph({
    children: [new TextRun({ text, size: 24 })],
    spacing: { after: 200 },
  });
}

async function loadImageForDocx(media) {
  try {
    if (isLegacyMediaRef(media)) {
      const src = media.dataUrl || media.thumbDataUrl;
      if (!src) return null;
      return dataUrlToDocxImage(src);
    }
    const url = await createMediaObjectUrl(media.id, { preferThumb: false });
    if (!url) return null;
    try {
      const res = await fetch(url);
      const blob = await res.blob();
      const buffer = await blob.arrayBuffer();
      const dims = await measureImage(url);
      return {
        data: new Uint8Array(buffer),
        type: blob.type?.includes('png') ? 'png' : 'jpg',
        aspect: dims.height / dims.width,
      };
    } finally {
      URL.revokeObjectURL(url);
    }
  } catch {
    return null;
  }
}

async function dataUrlToDocxImage(dataUrl) {
  const res = await fetch(dataUrl);
  const blob = await res.blob();
  const buffer = await blob.arrayBuffer();
  const dims = await measureImage(dataUrl);
  return {
    data: new Uint8Array(buffer),
    type: blob.type?.includes('png') ? 'png' : 'jpg',
    aspect: dims.height / dims.width,
  };
}

function measureImage(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve({ width: img.width, height: img.height });
    img.onerror = reject;
    img.src = src;
  });
}

function formatDateRange(trip) {
  const start = trip?.startDate;
  const end = trip?.endDate || (trip?.endedAt ? new Date(trip.endedAt).toISOString().slice(0, 10) : null);
  if (start && end) return `${start} → ${end}`;
  if (start) return start;
  return '';
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'trip';
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
